"""Create tables productions

Revision ID: eed5d67ac374
Revises: 7ca25bd27c15
Create Date: 2023-04-03 14:00:52.739580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed5d67ac374'
down_revision = '7ca25bd27c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.drop_column('budge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budge', sa.FLOAT(), nullable=True))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
